---28/02/2025---
CREATE TABLE USUARIO(
    ID_USUARIO NUMBER(3) PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    CORREO VARCHAR2(100),
    CONTRASEÑA VARCHAR2(9)
);

CREATE TABLE ORGANIZADOR(
    ID_ORGANIZADOR NUMBER(3) PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    CONTACTO VARCHAR2(100)
);

CREATE TABLE EVENTO(
    ID_EVENTO NUMBER(3) PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    FECHA DATE,
    DURACION NUMBER(10)
);

CREATE TABLE INSCRIPCION (
    ID_INSCRIPCION NUMBER(3) PRIMARY KEY
);

CREATE TABLE CATEGORIA (
    ID_CATEGORIA NUMBER(3) PRIMARY KEY,
    NOMBRE VARCHAR2(100)
);

CREATE TABLE UBICACION (
    ID_UBICACION NUMBER(3) PRIMARY KEY,
    TIPO VARCHAR2(100),
    DIRECCIÓN VARCHAR2(100)
);